### ISSUE TITLE
Unhandled exception when using OpenApi middleware

### ISSUE THREAD

**Issue by e-przestrzelski** [stryker-mutator/stryker-net#3379]
When running mutation testing locally for a project that uses OpenApi middleware: 

`builder.Services.AddOpenApi();` 
and 
`app.MapOpenApi();` 

I'm getting an unhandled exception from Stryker:

> 15:48:54 INF] Building project (...) using dotnet build xxx.csproj -c Debug --property:Platform=AnyCPU (directory ...)
> [15:49:05 WRN] Failed to load analyzer 'Microsoft.CodeAnalysis.Razor.Compiler':  (error : ReferencesNewerCompiler, analyzer: All).
> [15:49:05 WRN] The analyzer 'Microsoft.CodeAnalysis.Razor.Compiler' references a newer version (5.0.0.0) of the compiler than the one used by Stryker.NET.
> [15:49:06 WRN] Failed to load analyzer 'Microsoft.CodeAnalysis.Razor.Compiler':  (error : ReferencesNewerCompiler, analyzer: All).
> [15:49:06 WRN] The analyzer 'Microsoft.CodeAnalysis.Razor.Compiler' references a newer version (5.0.0.0) of the compiler than the one used by Stryker.NET.
> [15:49:07 WRN] An unidentified mutation in Microsoft.AspNetCore.OpenApi.SourceGenerators\Microsoft.AspNetCore.OpenApi.SourceGenerators.XmlCommentGenerator\OpenApiXmlCommentSupport.generated.cs resulted in a compile error (at 595:1) with id: CS9137, message: The 'interceptors' feature is not enabled in this namespace. Add '<InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>' to your project. (Source code: global::System.Runtime.CompilerServices.InterceptsLocationAttribute)
> [15:49:07 INF] Safe Mode! Stryker will remove all mutations in AddOpenApi and mark them as 'compile error'.
> [15:49:07 FTL] Stryker.NET could not compile the project after mutation. This is probably an error for Stryker.NET and not your project. Please report this issue on github with the previous error message.
> Unhandled exception. System.AggregateException: One or more errors occurred. (Internal error due to compile error.)
>  ---> Stryker.Abstractions.Exceptions.CompilationException: Internal error due to compile error.
>    at Stryker.Core.Compiling.CSharpRollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics, Boolean lastAttempt, Boolean devMode) in /_/src/Stryker.Core/Stryker.Core/Compiling/CSharpRollbackProcess.cs:line 75
>    at Stryker.Core.Compiling.CsharpCompilingProcess.TryCompilation(Stream ms, Stream symbolStream, CSharpCompilation& compilation, EmitResult previousEmitResult, Boolean lastAttempt, Int32 retryCount) in /_/src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs:line 185
>    at Stryker.Core.Compiling.CsharpCompilingProcess.Compile(IEnumerable`1 syntaxTrees, Stream ilStream, Stream symbolStream) in /_/src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs:line 82
>    at Stryker.Core.MutationTest.CsharpMutationProcess.CompileMutations(MutationTestInput input, CsharpCompilingProcess compilingProcess) in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 72
>    at Stryker.Core.MutationTest.CsharpMutationProcess.Mutate(MutationTestInput input, IStrykerOptions options) in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 62
>    at Stryker.Core.MutationTest.MutationTestProcess.Mutate() in /_/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs:line 65
>    at Stryker.Core.Initialisation.ProjectMutator.MutateProject(IStrykerOptions options, MutationTestInput input, IReporter reporters) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs:line 43
>    at Stryker.Core.Initialisation.ProjectOrchestrator.<>c__DisplayClass8_0.<MutateProjects>b__0(MutationTestInput mutationTestInput) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 76
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
> --- End of stack trace from previous location ---
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
>    at System.Threading.Tasks.TaskReplicator.Replica.Execute()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
>    at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
> --- End of stack trace from previous location ---
>    at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
>    at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(IStrykerOptions options, IReporter reporters, ITestRunner runner) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 74
>    at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 59
>    at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 153
>    at Stryker.CLI.StrykerCli.<>c__DisplayClass11_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 125
>    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
>    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
>    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
>    at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 131
>    at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 25

I've tried adding the "problematic" file that is source-generated to the ignored list, even tried using wildcard:
`-m "!**/*generated.cs"`
but this doesn't change anything.

I've tried adding: `<InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>`
as well, but it doesn't help either.

**Comment by rouke-broersma** [comment]
Is this on Linux?

**Comment by e-przestrzelski** [comment]
@rouke-broersma no, this is Windows 11, running from PowerShell 7.5.4

**Comment by dupdob** [comment]
The problem is revealed by this log line:
`[15:49:05 WRN] Failed to load analyzer 'Microsoft.CodeAnalysis.Razor.Compiler': (error : ReferencesNewerCompiler, analyzer: All).` 

The Razor compiler referenced by your project failed to load because it needs a compiler version that is more recent than the one Stryker is using internally.

We have yet to release a version of Stryker build against Roslyn 5.0; we are stuck at 4.14 for now.

**Comment by Frulfump** [comment]
> The problem is revealed by this log line:
> `[15:49:05 WRN] Failed to load analyzer 'Microsoft.CodeAnalysis.Razor.Compiler': (error : ReferencesNewerCompiler, analyzer: All).` 
> 
> The Razor compiler referenced by your project failed to load because it needs a compiler version that is more recent than the one Stryker is using internally.
> 
> We have yet to release a version of Stryker build against Roslyn 5.0; we are stuck at 4.14 for now.

So should be fixed by
#3353?

**Comment by dupdob** [comment]
yes, it should be

**Comment by rouke-broersma** [comment]
@e-przestrzelski @Frulfump  I fixed the issues I had with csharp14 in the integration test and I will release a new version shortly. Please let us know if you still experience any issues after updating.

**Comment by e-przestrzelski** [comment]
@rouke-broersma I'm still experiencing the same (or very similar) issue when using version 4.10.0:

> [08:56:55 WRN] An unidentified mutation in Microsoft.AspNetCore.OpenApi.SourceGenerators\Microsoft.AspNetCore.OpenApi.SourceGenerators.XmlCommentGenerator\OpenApiXmlCommentSupport.generated.cs resulted in a compile error (at 595:1) with id: CS9137, message: The 'interceptors' feature is not enabled in this namespace. Add '<InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>' to your project. (Source code: global::System.Runtime.CompilerServices.InterceptsLocationAttribute)
> [08:56:55 INF] Safe Mode! Stryker will remove all mutations in AddOpenApi and mark them as 'compile error'.
> [08:56:55 FTL] Stryker.NET could not compile the project after mutation. This is probably an error for Stryker.NET and not your project. Please report this issue on github with the previous error message.
> [08:56:55 ERR] An error occurred during the mutation test run
> System.AggregateException: One or more errors occurred. (Internal error due to compile error.)
>  ---> Stryker.Abstractions.Exceptions.CompilationException: Internal error due to compile error.
>    at Stryker.Core.Compiling.CSharpRollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics, Boolean lastAttempt, Boolean devMode) in /_/src/Stryker.Core/Stryker.Core/Compiling/CSharpRollbackProcess.cs:line 75
>    at Stryker.Core.Compiling.CsharpCompilingProcess.TryCompilation(Stream ms, Stream symbolStream, CSharpCompilation& compilation, EmitResult previousEmitResult, Boolean lastAttempt, Int32 retryCount) in /_/src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs:line 185
>    at Stryker.Core.Compiling.CsharpCompilingProcess.Compile(IEnumerable`1 syntaxTrees, Stream ilStream, Stream symbolStream) in /_/src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs:line 82
>    at Stryker.Core.MutationTest.CsharpMutationProcess.CompileMutations(MutationTestInput input, CsharpCompilingProcess compilingProcess) in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 72
>    at Stryker.Core.MutationTest.CsharpMutationProcess.Mutate(MutationTestInput input, IStrykerOptions options) in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 62
>    at Stryker.Core.MutationTest.MutationTestProcess.Mutate() in /_/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs:line 65
>    at Stryker.Core.Initialisation.ProjectMutator.MutateProject(IStrykerOptions options, MutationTestInput input, IReporter reporters) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs:line 43
>    at Stryker.Core.Initialisation.ProjectOrchestrator.<>c__DisplayClass8_0.<MutateProjects>b__0(MutationTestInput mutationTestInput) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 76
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
> --- End of stack trace from previous location ---
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
>    at System.Threading.Tasks.TaskReplicator.Replica.Execute()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
>    at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
> --- End of stack trace from previous location ---
>    at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
>    at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(IStrykerOptions options, IReporter reporters, ITestRunner runner) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 74
>    at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 59
> [08:56:55 INF] Time Elapsed 00:00:32.3910992
> Unhandled exception. System.AggregateException: One or more errors occurred. (Internal error due to compile error.)
>  ---> Stryker.Abstractions.Exceptions.CompilationException: Internal error due to compile error.
>    at Stryker.Core.Compiling.CSharpRollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics, Boolean lastAttempt, Boolean devMode) in /_/src/Stryker.Core/Stryker.Core/Compiling/CSharpRollbackProcess.cs:line 75
>    at Stryker.Core.Compiling.CsharpCompilingProcess.TryCompilation(Stream ms, Stream symbolStream, CSharpCompilation& compilation, EmitResult previousEmitResult, Boolean lastAttempt, Int32 retryCount) in /_/src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs:line 185
>    at Stryker.Core.Compiling.CsharpCompilingProcess.Compile(IEnumerable`1 syntaxTrees, Stream ilStream, Stream symbolStream) in /_/src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs:line 82
>    at Stryker.Core.MutationTest.CsharpMutationProcess.CompileMutations(MutationTestInput input, CsharpCompilingProcess compilingProcess) in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 72
>    at Stryker.Core.MutationTest.CsharpMutationProcess.Mutate(MutationTestInput input, IStrykerOptions options) in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 62
>    at Stryker.Core.MutationTest.MutationTestProcess.Mutate() in /_/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs:line 65
>    at Stryker.Core.Initialisation.ProjectMutator.MutateProject(IStrykerOptions options, MutationTestInput input, IReporter reporters) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs:line 43
>    at Stryker.Core.Initialisation.ProjectOrchestrator.<>c__DisplayClass8_0.<MutateProjects>b__0(MutationTestInput mutationTestInput) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 76
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
> --- End of stack trace from previous location ---
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
>    at System.Threading.Tasks.TaskReplicator.Replica.Execute()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
>    at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
> --- End of stack trace from previous location ---
>    at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
>    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
>    at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(IStrykerOptions options, IReporter reporters, ITestRunner runner) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 74
>    at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 59
>    at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 153
>    at Stryker.CLI.StrykerCli.<>c__DisplayClass11_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 125
>    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
>    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
>    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
>    at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 131
>    at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 26

**Comment by rouke-broersma** [comment]
@e-przestrzelski this is a completely different error, the original problem is solved. For this problem a new issue was submitted: #3397 

I do not yet know why this would happen, generated code should not be mutated.

**Comment by aannenko** [comment]
A tiny detail.
1. .NET 10 now has [interceptors](https://github.com/dotnet/roslyn/blob/main/docs/features/interceptors.md) enabled by default.
2. ASP.NET Core 10 features like [`AddOpenApi`/`MapOpenApi`](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/aspnetcore-openapi?view=aspnetcore-10.0) and Minimal API [Validation](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-10.0?view=aspnetcore-10.0#validation-support-in-minimal-apis) use interceptors for their purposes.
3. Stryker uses Roslyn 4.14 where interceptors are disabled by default.
3. ASSUMPTION: The authors of Stryker need to [opt-in](https://github.com/dotnet/roslyn/blob/main/docs/features/interceptors.md#user-opt-in) to use interceptors, otherwise anything Stryker attempts to recompile, if it uses interceptors, will fail to compile with "CS9137, message: The 'interceptors' feature is not enabled in this namespace."

**Comment by rouke-broersma** [comment]
@aannenko thank you that is very useful!

**Comment by aannenko** [comment]
Not a problem!
I believe a basic app created with a command  `dotnet new webapi` using .NET 10 CLI could be used as a test subject for Stryker to try to mutate it and see if it compiles - this basic app will use OpenAPI from the start.

**Comment by e-przestrzelski** [comment]
@rouke-broersma  are there any updates on this? I was hoping to include mutation testing in my pipelines for some .NET 10 applications, but this prevents me from doing so. I'm not sure if opting in to use interceptors has it's own risks or if there is any workaround for that.

**Comment by rouke-broersma** [comment]
@e-przestrzelski based on information by @aannenko I created issue #3402, we have done some initial investigation into what we might need to do to support this but as far as I know no one has started on an implementation at this time. It seems fairly straight forward, but I am unsure as to the risks because we don't have experience with this dotnet feature.

**Comment by aannenko** [comment]
Because the Interceptors are essentially a source generated code, I believe we could treat them as such, and whatever rules we had related to source generated code, we could apply them to the interceptors.

**Comment by fabio-dev** [comment]
I created this PR [!3471](https://github.com/stryker-mutator/stryker-net/pull/3471) to try to fix this issue, as I need to run Stryker on a .net 10 WebApi. Please feel free to take a look and check if it could be OK.
